In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("adityaramachandran27/world-air-quality-index-by-city-and-coordinates")
print("Path to dataset files:", path)
print(os.listdir(path))
csv_file = "AQI and Lat Long of Countries.csv"  
file_path = os.path.join(path, csv_file)
df = pd.read_csv(file_path)

Path to dataset files: C:\Users\jason\.cache\kagglehub\datasets\adityaramachandran27\world-air-quality-index-by-city-and-coordinates\versions\1
['AQI and Lat Long of Countries.csv']

In [3]:
# check for null values
df.isnull().sum()

Country               302
City                    0
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
lat                     0
lng                     0
dtype: int64

In [4]:
# Drop rows with any null values
df.dropna(inplace=True)

In [5]:
# Get a sum of rows with duplicate city names
df['City'].duplicated().sum()

2437

In [6]:
# Drop rows with duplicated city names but keep the first duplicate
df.drop_duplicates(subset=['City'], keep='first', inplace=True) 
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,lat,lng
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate,44.7444,44.2031
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-5.2900,-44.4900
3,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate,37.1667,15.1833
4,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good,53.0167,20.8833
5,United States of America,Punta Gorda,54,Moderate,1,Good,14,Good,11,Good,54,Moderate,16.1005,-88.8074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16689,China,Shaoguan,160,Unhealthy,3,Good,160,Unhealthy,1,Good,79,Moderate,24.8011,113.5927
16690,United States of America,Highland Springs,54,Moderate,1,Good,34,Good,5,Good,54,Moderate,37.5516,-77.3285
16691,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,49.0650,18.9219
16693,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good,48.7786,2.2906
16694,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate,40.1241,-82.9210

In [7]:
# Reset index
df.reset_index(drop=True)
df

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,lat,lng
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate,44.7444,44.2031
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-5.2900,-44.4900
3,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate,37.1667,15.1833
4,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good,53.0167,20.8833
5,United States of America,Punta Gorda,54,Moderate,1,Good,14,Good,11,Good,54,Moderate,16.1005,-88.8074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16689,China,Shaoguan,160,Unhealthy,3,Good,160,Unhealthy,1,Good,79,Moderate,24.8011,113.5927
16690,United States of America,Highland Springs,54,Moderate,1,Good,34,Good,5,Good,54,Moderate,37.5516,-77.3285
16691,Slovakia,Martin,71,Moderate,1,Good,39,Good,1,Good,71,Moderate,49.0650,18.9219
16693,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good,48.7786,2.2906
16694,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate,40.1241,-82.9210

In [8]:
df.columns

Index(['Country', 'City', 'AQI Value', 'AQI Category', 'CO AQI Value',
       'CO AQI Category', 'Ozone AQI Value', 'Ozone AQI Category',
       'NO2 AQI Value', 'NO2 AQI Category', 'PM2.5 AQI Value',
       'PM2.5 AQI Category', 'lat', 'lng'],
      dtype='object')

In [9]:
# Change column names
df.columns = ['Country','City','AQI_value','AQI_category','CO_AQI_value','CO_AQI_category',
              'Ozone_AQI_value','Ozone_AQI_category','NO2_AQI_value','NO2_AQI_category',
              'PM2_5_AQI_value','PM2_5_AQI_category','latitude','longitude']
df.head()

,Country,City,AQI_value,AQI_category,CO_AQI_value,CO_AQI_category,Ozone_AQI_value,Ozone_AQI_category,NO2_AQI_value,NO2_AQI_category,PM2_5_AQI_value,PM2_5_AQI_category,latitude,longitude
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate,44.7444,44.2031
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good,-5.2900,-44.4900
3,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate,37.1667,15.1833
4,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good,53.0167,20.8833
5,United States of America,Punta Gorda,54,Moderate,1,Good,14,Good,11,Good,54,Moderate,16.1005,-88.8074

In [10]:
# Export cleansed data
df.to_csv('world_AQI_cleaned.csv', index=False)