In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('elections.psv', delimiter ='|')
df.replace({'|': ','}, regex=True)
df

,Election ID,Election Title,Society ID,Start Date,End Date
0,1,2000 Steering Committee Elections,1,2000-04-20,2000-05-21
1,2,2001 Board Elections,1,2001-07-21,2001-09-12
2,3,2002 Council Member Elections,1,2002-02-22,2002-04-03
3,4,2003 Executive Board Elections,1,2003-10-22,2003-12-06
4,5,2004 Officer Appointments,1,2004-05-20,2004-07-17
...,...,...,...,...,...
1995,1996,2020 Governing Body Elections,80,2020-06-03,2020-07-21
1996,1997,2021 Committee Chairperson Selection,80,2021-05-22,2021-07-04
1997,1998,2022 Executive Board Elections,80,2022-09-28,2022-10-31
1998,1999,2023 Director Elections,80,2023-08-24,2023-09-27
1999,2000,2024 Trustee Elections,80,2024-06-30,2024-08-28

In [14]:
df.isnull().sum()

Election ID       0
Election Title    0
Society ID        0
Start Date        0
End Date          0
dtype: int64

In [15]:
df.duplicated().sum()

0

In [18]:
df.columns = ['election_id', 'election_title', 'society_id', 'start_date', 'end_date']
df

,election_id,election_title,society_id,start_date,end_date
0,1,2000 Steering Committee Elections,1,2000-04-20,2000-05-21
1,2,2001 Board Elections,1,2001-07-21,2001-09-12
2,3,2002 Council Member Elections,1,2002-02-22,2002-04-03
3,4,2003 Executive Board Elections,1,2003-10-22,2003-12-06
4,5,2004 Officer Appointments,1,2004-05-20,2004-07-17
...,...,...,...,...,...
1995,1996,2020 Governing Body Elections,80,2020-06-03,2020-07-21
1996,1997,2021 Committee Chairperson Selection,80,2021-05-22,2021-07-04
1997,1998,2022 Executive Board Elections,80,2022-09-28,2022-10-31
1998,1999,2023 Director Elections,80,2023-08-24,2023-09-27
1999,2000,2024 Trustee Elections,80,2024-06-30,2024-08-28

In [17]:
df.to_csv('elections.csv', index=False)