In [32]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('candidates.psv', delimiter ='|', dtype ={'CandidateId': int, 'MemberID':int, 'SocietyID': int, 'Allowed Votes': int})
df.replace({'|': ','}, regex=True)
df

,Candidate ID,Office ID,Election ID,Office Name,Allowed Votes,Candidate First Name,Candidate Last Name,Candidate Credentials,Candidate Bio
0,1,1,1,Treasurer,1,Gabriel,Lawrence,EdD,With a background in psychology and a passion ...
1,2,2,1,President,1,Billy,Howard,MPA,NaN
2,3,2,1,President,1,Justin,Stewart,DVM,NaN
3,4,2,1,President,1,Amy,Bishop,DPT,NaN
4,5,2,1,President,1,Anna,Rodriguez,DPT,NaN
...,...,...,...,...,...,...,...,...,...
12446,12447,4965,1999,President,1,Shirley,Hicks,NaN,NaN
12447,12448,4966,2000,Vice President,2,Ann,Rice,NaN,NaN
12448,12449,4966,2000,Vice President,2,Susan,Parker,MFA,NaN
12449,12450,4966,2000,Vice President,2,Edward,Reid,NaN,NaN
12450,12451,4966,2000,Vice President,2,Patrick,Sullivan,NaN,NaN

In [39]:
df.duplicated().sum()

0

In [43]:
df.isnull().sum()

Candidate ID                 0
Office ID                    0
Election ID                  0
Office Name                  0
Allowed Votes                0
Candidate First Name         0
Candidate Last Name          0
Candidate Credentials     6228
Candidate Bio            11204
dtype: int64

In [46]:
df.columns = ['candidate_id', 'office_id', 'election_id', 'office_name', 'allowed_votes', 'candidate_first_name', 'candidate_last_name', 'candidate_credentials', 'candidate_bio']
df

,candidate_id,office_id,election_id,office_name,allowed_votes,candidate_first_name,candidate_last_name,candidate_credentials,candidate_bio
0,1,1,1,Treasurer,1,Gabriel,Lawrence,EdD,With a background in psychology and a passion ...
1,2,2,1,President,1,Billy,Howard,MPA,NaN
2,3,2,1,President,1,Justin,Stewart,DVM,NaN
3,4,2,1,President,1,Amy,Bishop,DPT,NaN
4,5,2,1,President,1,Anna,Rodriguez,DPT,NaN
...,...,...,...,...,...,...,...,...,...
12446,12447,4965,1999,President,1,Shirley,Hicks,NaN,NaN
12447,12448,4966,2000,Vice President,2,Ann,Rice,NaN,NaN
12448,12449,4966,2000,Vice President,2,Susan,Parker,MFA,NaN
12449,12450,4966,2000,Vice President,2,Edward,Reid,NaN,NaN
12450,12451,4966,2000,Vice President,2,Patrick,Sullivan,NaN,NaN

In [47]:
df.to_csv('candidates.csv', index=False)