In [4]:
import pandas as pd 
import numpy as np

In [5]:
df = pd.read_csv('members.psv', delimiter ='|')
df.replace({'|': ','}, regex=True)
df

,Member ID,First Name,Last Name,Username,Society ID,Role
0,1,Judith,King,starbreeze10,12,member
1,2,Roger,Nichols,grapefruitsnowstorm10,5,member
2,3,Alexander,Harris,lemonrain8,19,member
3,4,Roger,Lawrence,macadamiaturtle6,42,member
4,5,Nancy,Foster,raspberryslush7,24,member
...,...,...,...,...,...,...
19995,19996,Andrew,Cooper,pistachiofox20,4,member
19996,19997,Christine,Pearson,tigerice18,28,member
19997,19998,Stephen,Jones,applewater17,22,member
19998,19999,Elizabeth,Ellis,dragonfly9,59,member
19999,20000,Larry,Henry,seastorm3,18,member

In [6]:
df.columns = ['member_id', 'first_name', 'last_name', 'username', 'society_id', 'role']
df

,member_id,first_name,last_name,username,society_id,role
0,1,Judith,King,starbreeze10,12,member
1,2,Roger,Nichols,grapefruitsnowstorm10,5,member
2,3,Alexander,Harris,lemonrain8,19,member
3,4,Roger,Lawrence,macadamiaturtle6,42,member
4,5,Nancy,Foster,raspberryslush7,24,member
...,...,...,...,...,...,...
19995,19996,Andrew,Cooper,pistachiofox20,4,member
19996,19997,Christine,Pearson,tigerice18,28,member
19997,19998,Stephen,Jones,applewater17,22,member
19998,19999,Elizabeth,Ellis,dragonfly9,59,member
19999,20000,Larry,Henry,seastorm3,18,member

In [7]:
df.isnull().sum()

member_id     0
first_name    0
last_name     0
username      0
society_id    0
role          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
import random
import string

In [10]:
# Function to generate a secure password (excluding commas)
def generate_password(length=15):
    if length < 10:  # Ensure minimum length for required characters
        raise ValueError("Password length must be at least 10")

    # Define characters excluding commas
    special_chars = string.punctuation.replace(",", "")  # Remove commas
    all_chars = string.ascii_letters + string.digits + special_chars

    # Ensure at least one uppercase, one number, and one special character (excluding comma)
    upper = random.choice(string.ascii_uppercase)
    lower = random.choice(string.ascii_lowercase)
    digit = random.choice(string.digits)
    special = random.choice(special_chars)

    # Generate remaining random characters
    remaining_length = length - 3
    other_chars = ''.join(random.choices(all_chars, k=remaining_length))

    # Shuffle the password to ensure randomness
    password = list(upper + lower + digit + special + other_chars)
    random.shuffle(password)

    return ''.join(password)

# Add 'password' column with generated passwords
df['password'] = [generate_password() for _ in range(len(df))]

# Display the updated DataFrame
df

,member_id,first_name,last_name,username,society_id,role,password
0,1,Judith,King,starbreeze10,12,member,BoJx:Z[O$7b={+v_
1,2,Roger,Nichols,grapefruitsnowstorm10,5,member,eVIX7Fu&{nwaj0lC
2,3,Alexander,Harris,lemonrain8,19,member,'s(>eKH2@.ns9:vN
3,4,Roger,Lawrence,macadamiaturtle6,42,member,"FI]+t=5qrq""&6$Q["
4,5,Nancy,Foster,raspberryslush7,24,member,X3K/ch/7Cg=[1_)7
...,...,...,...,...,...,...,...
19995,19996,Andrew,Cooper,pistachiofox20,4,member,8@?o+zpI]~d265LT
19996,19997,Christine,Pearson,tigerice18,28,member,@(pD6[9L9sDzt~=%
19997,19998,Stephen,Jones,applewater17,22,member,-iS.LSuUPJmjWZ6M
19998,19999,Elizabeth,Ellis,dragonfly9,59,member,9ele@E=%#QF}]B6w
19999,20000,Larry,Henry,seastorm3,18,member,o#i}Dq8k/OEOQl~0

In [11]:
df.to_csv('members.csv', index=False)