In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('votes.psv', delimiter ='|')
df.replace({'|': ','}, regex=True)
df

         Member ID  Election ID  Office ID  Candidate ID
0                1          276        696        1737.0
1                1          276        697        1739.0
2                1          276        698        1741.0
3                1          277        699        1746.0
4                1          277        700        1750.0
...            ...          ...        ...           ...
1395087      20000          449       1141        2839.0
1395088      20000          449       1142        2841.0
1395089      20000          449       1142        2840.0
1395090      20000          449       1143        2844.0
1395091      20000          450       1144        2847.0

[1395092 rows x 4 columns]

In [31]:
df.isnull().sum()

Member ID           0
Election ID         0
Office ID           0
Candidate ID    39454
dtype: int64

In [32]:
df.duplicated().sum()

0

In [33]:
df.columns = ['member_id', 'election_id', 'office_id', 'candidate_id']
df

         member_id  election_id  office_id  candidate_id
0                1          276        696        1737.0
1                1          276        697        1739.0
2                1          276        698        1741.0
3                1          277        699        1746.0
4                1          277        700        1750.0
...            ...          ...        ...           ...
1395087      20000          449       1141        2839.0
1395088      20000          449       1142        2841.0
1395089      20000          449       1142        2840.0
1395090      20000          449       1143        2844.0
1395091      20000          450       1144        2847.0

[1395092 rows x 4 columns]

In [43]:
df['candidate_id'] = df['candidate_id'].astype('Int64')
df

         member_id  election_id  office_id  candidate_id
0                1          276        696          1737
1                1          276        697          1739
2                1          276        698          1741
3                1          277        699          1746
4                1          277        700          1750
...            ...          ...        ...           ...
1395087      20000          449       1141          2839
1395088      20000          449       1142          2841
1395089      20000          449       1142          2840
1395090      20000          449       1143          2844
1395091      20000          450       1144          2847

[1395092 rows x 4 columns]

In [44]:
df.isnull().sum()

member_id           0
election_id         0
office_id           0
candidate_id    39454
dtype: int64

In [45]:
df.to_csv('votes.csv', index=False)